site_project/noteapp/urls.py
from django.urls import path
from . import views

app_name = 'noteapp'

urlpatterns = [
    path('', views.main, name='main'),
]

site_project/quotes_list/urls.py
from django.urls import path
from . import views

app_name = 'quotes_list'

urlpatterns = [
    path('', views.main, name='main'),
    path('page/<int:page>', views.main, name = "root_paginator"),
    path('create-author/', views.create_author, name='create_author'),
    path('create-quote/', views.create_quote, name='create_quote'),
    path('detail/<int:author_id>', views.author_details, name='author_details'),
    path('create-tag/', views.tag, name = 'tag'),
    path('tags/<int:tags_id>', views.tags_list, name= 'tags_list'),
    path('script/', views.script, name='script'),
]

site_project/site_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotes_list.urls')),
    path('users/', include('users.urls')),
]

site_project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.log_out_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('script/', views.script, name='script'),
]

site_project/noteapp/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class Authors(models.Model):

    fullname = models.CharField(max_length=200)
    born_date = models.DateField()
    born_location = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)

    def __str__(self):
        return f"{self.fullname}"



class Quotes(models.Model):
    tags = ArrayField(models.CharField(max_length=30), size=10)
    author = models.ForeignKey(Authors, on_delete=models.CASCADE)
    quote = models.CharField(max_length=2000)

    def __str__(self):
        return f"{self.quote}, {self.author}. Tags: {self.tags}"


class UsersSite(models.Model):
    nickname = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    login = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.nickname}"

site_project/quotes_list/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class Authors(models.Model):

    fullname = models.CharField(max_length=200, unique=True)
    born_date = models.DateField()
    born_location = models.CharField(max_length=200)
    description = models.CharField(max_length=20000)
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fullname}"

class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Quotes(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Authors, on_delete=models.CASCADE)
    quote = models.CharField(max_length=20000)
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quote}, {self.author}. Tags: {self.tags}"

site_project/quotes_list/forms.py
from django import forms
from . import models
from django.forms import ModelForm, ModelMultipleChoiceField
from .models import Authors, Quotes, Tag

class CreateQuoteForm(ModelForm):
    author = forms.ModelChoiceField(queryset = Authors.objects.all(), widget=forms.Select(attrs={'class':'dropdown'}))
    quote = forms.CharField(max_length=1000, required=True, widget=forms.TextInput())
    # author = forms.CharField(max_length=1000, required=True, widget=forms.TextInput())


    class Meta:
        model = Quotes
        fields = ["quote", "author"]
        exclude = ['tags']


class CreateAuthorForm(ModelForm):
    fullname = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    born_date = forms.DateField(required=True, widget=forms.DateInput())
    born_location = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    description = forms.CharField(max_length=1000, required=True, widget=forms.TextInput())

    class Meta:
        model = Authors
        fields = ["fullname", "born_date", "born_location", "description"]


class TagForm(ModelForm):
    name = forms.CharField(min_length=3, max_length=25, required=True, widget=forms.TextInput())

    class Meta:
        model = Tag
        fields = ['name']

site_project/noteapp/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render


# Create your views here.
def main(request):
    return render(request, 'noteapp/index.html')

site_project/quotes_list/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import CreateQuoteForm, CreateAuthorForm, TagForm
from .models import Authors, Quotes, Tag
from django.core.paginator import Paginator
import json




# Create your views here.
def main(request, page = 1):
    quotes_list = Quotes.objects.all()
    # per_page = 100
    # paginator = Paginator(quotes_list, per_page)
    # quotes_on_page = paginator.page(page)
    return render(request, 'quotes_list/index.html', context={"quotes_list": quotes_list})

@login_required
def create_author(request):
    if request.method == 'POST':
        form = CreateAuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_list:main')
        else:
            return render(request, 'quotes_list/create_author.html', context={"form": form, "message": "Author not created!"})

    return render(request, 'quotes_list/create_author.html', context={"form": CreateAuthorForm()})


@login_required
def create_quote(request):
    tags = Tag.objects.all()
    authors = Authors.objects.all()


    if request.method == 'POST':
        form = CreateQuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            form.fields["author"].queryset = Authors.objects.filter(fullname=form.cleaned_data['author'])

            return redirect(to='quotes_list:main')
        else:
            return render(request, 'quotes_list/create_quote.html', context={"tags": tags, "authors": authors, 'form': form, "message": "Quotes not created!"})

    return render(request, 'quotes_list/create_quote.html', context={"tags": tags, "authors": authors, 'form': CreateQuoteForm()})

def author_details(request, author_id):
    author = get_object_or_404(Authors, pk = author_id)
    return render(request, 'quotes_list/author_details.html', {"author": author})



def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_list:main')
        else:
            return render(request, 'quotes_list/tag.html', context={'form': form, "message": "Tag not created!"})

    return render(request, 'quotes_list/tag.html', context={'form': TagForm()})

def tags_list(request, tag_id):
    quotes = Quotes.objects.all()
    return render(request, 'quotes_list/tags_list.html', context={"quotes": quotes})

def top_ten_tags(request):
    top_tags = Tag.objects.all()[:9]
    return render(request, "quotes_list/index.html", context={"top_tags":top_tags})

@login_required
def script(request):
    with open("script/authors.json") as fh:
        authors = json.load(fh)

    for author in authors:
        Authors.objects.get_or_create(fullname=author["fullname"], born_date=author["born_date"],
                                      born_location=author["born_location"], description=author["description"])

    with open("script/quotes.json") as fh:
        quotes = json.load(fh)

    for quote in quotes:
        tags = []
        tags_list_file = quote["tags"].removeprefix("[").removesuffix("]").split(",")
        for tag in tags_list_file:
            t, *_ = Tag.objects.get_or_create(name=tag.strip().removeprefix("'").removesuffix("'"))
            tags.append(t)
        exist_quote = bool(len(Quotes.objects.filter(quote=quote["quote"])))

        if not exist_quote:
            au = Authors.objects.get(fullname=quote["author"])
            qu = Quotes.objects.create(quote=quote['quote'], author=au)
            for tag in tags:
                qu.tags.add(tag)

    return redirect(to='quotes_list:main')

site_project/quotes_list/templates/noteapp/author.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:tag' %}" xmlns="http://www.w3.org/1999/html">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Born: {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
        <span>{{author.</span>
    </div>
</form>

{% endblock %}

site_project/quotes_list/templates/noteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'noteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

site_project/quotes_list/templates/noteapp/create_quote.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.title }}
        </label>
        <span>{{ form.errors.title }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

site_project/quotes_list/templates/noteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>My site</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <h1>Main page</h1>
</main>
</body>
</html>