site_project/quotes_list/urls.py
from django.urls import path
from . import views

app_name = 'quotes_list'

urlpatterns = [
    path('', views.main, name='main'),
    path('page/<int:page>', views.main, name = "root_paginator"),
    path('create-author/', views.create_author, name='create_author'),
    path('create-quote/', views.create_quote, name='create_quote'),
    path('detail/<int:author_id>', views.author_details, name='author_details'),
    path('create-tag/', views.tag, name = 'tag'),
    path('tags/<int:tags_id>', views.tags_list, name= 'tags_list'),
    path('script/', views.script, name='script'),
]

site_project/site_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quotes_list.urls')),
    path('users/', include('users.urls')),
]

site_project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.log_out_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('script/', views.script, name='script'),
]

site_project/quotes_list/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.


class Authors(models.Model):

    fullname = models.CharField(max_length=200, unique=True)
    born_date = models.DateField()
    born_location = models.CharField(max_length=200)
    description = models.CharField(max_length=20000)
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.fullname}"

class Tag(models.Model):
    name = models.CharField(max_length=100, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Quotes(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Authors, on_delete=models.CASCADE)
    quote = models.CharField(max_length=20000)
    # created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.quote}, {self.author}. Tags: {self.tags}"

site_project/quotes_list/forms.py
from django import forms
from . import models
from django.forms import ModelForm, ModelMultipleChoiceField
from .models import Authors, Quotes, Tag

class CreateQuoteForm(ModelForm):
    author = forms.ModelChoiceField(queryset = Authors.objects.all(), widget=forms.Select(attrs={'class':'dropdown'}))
    quote = forms.CharField(max_length=1000, required=True, widget=forms.TextInput())
    # author = forms.CharField(max_length=1000, required=True, widget=forms.TextInput())


    class Meta:
        model = Quotes
        fields = ["quote", "author"]
        exclude = ['tags']


class CreateAuthorForm(ModelForm):
    fullname = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    born_date = forms.DateField(required=True, widget=forms.DateInput())
    born_location = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    description = forms.CharField(max_length=1000, required=True, widget=forms.TextInput())

    class Meta:
        model = Authors
        fields = ["fullname", "born_date", "born_location", "description"]


class TagForm(ModelForm):
    name = forms.CharField(min_length=3, max_length=25, required=True, widget=forms.TextInput())

    class Meta:
        model = Tag
        fields = ['name']

site_project/quotes_list/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import CreateQuoteForm, CreateAuthorForm, TagForm
from .models import Authors, Quotes, Tag
from django.core.paginator import Paginator
import json




# Create your views here.
def main(request, page = 1):
    quotes_list = Quotes.objects.all()
    # per_page = 100
    # paginator = Paginator(quotes_list, per_page)
    # quotes_on_page = paginator.page(page)
    return render(request, 'quotes_list/index.html', context={"quotes_list": quotes_list})

@login_required
def create_author(request):
    if request.method == 'POST':
        form = CreateAuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_list:main')
        else:
            return render(request, 'quotes_list/create_author.html', context={"form": form, "message": "Author not created!"})

    return render(request, 'quotes_list/create_author.html', context={"form": CreateAuthorForm()})


@login_required
def create_quote(request):
    tags = Tag.objects.all()
    authors = Authors.objects.all()


    if request.method == 'POST':
        form = CreateQuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            form.fields["author"].queryset = Authors.objects.filter(fullname=form.cleaned_data['author'])

            return redirect(to='quotes_list:main')
        else:
            return render(request, 'quotes_list/create_quote.html', context={"tags": tags, "authors": authors, 'form': form, "message": "Quotes not created!"})

    return render(request, 'quotes_list/create_quote.html', context={"tags": tags, "authors": authors, 'form': CreateQuoteForm()})

def author_details(request, author_id):
    author = get_object_or_404(Authors, pk = author_id)
    return render(request, 'quotes_list/author_details.html', {"author": author})



def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotes_list:main')
        else:
            return render(request, 'quotes_list/tag.html', context={'form': form, "message": "Tag not created!"})

    return render(request, 'quotes_list/tag.html', context={'form': TagForm()})

def tags_list(request, tag_id):
    quotes = Quotes.objects.all()
    return render(request, 'quotes_list/tags_list.html', context={"quotes": quotes})

def top_ten_tags(request):
    top_tags = Tag.objects.all()[:9]
    return render(request, "quotes_list/index.html", context={"top_tags":top_tags})

@login_required
def script(request):
    with open("script/authors.json") as fh:
        authors = json.load(fh)

    for author in authors:
        Authors.objects.get_or_create(fullname=author["fullname"], born_date=author["born_date"],
                                      born_location=author["born_location"], description=author["description"])

    with open("script/quotes.json") as fh:
        quotes = json.load(fh)

    for quote in quotes:
        tags = []
        tags_list_file = quote["tags"].removeprefix("[").removesuffix("]").split(",")
        for tag in tags_list_file:
            t, *_ = Tag.objects.get_or_create(name=tag.strip().removeprefix("'").removesuffix("'"))
            tags.append(t)
        exist_quote = bool(len(Quotes.objects.filter(quote=quote["quote"])))

        if not exist_quote:
            au = Authors.objects.get(fullname=quote["author"])
            qu = Quotes.objects.create(quote=quote['quote'], author=au)
            for tag in tags:
                qu.tags.add(tag)

    return redirect(to='quotes_list:main')

site_project/quotes_list/templates/quotes_list/author_details.html
{% extends "quotes_list/base.html" %} {% block content %}

<h1>{{author.fullname}}</h1>
<p><b>Born:</b> {{author.born_date}}</p>
<p><b>Born location:</b> {{author.born_location}}</p>
<p><b>Description:</b> {{author.description}}</p>
{% endblock %}

site_project/quotes_list/templates/quotes_list/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/main.css">
</head>
<body>
<!--    <nav class="col-md-4" >-->
<!--        <a href="/" role="button" > Go back to the main page </a>-->
<!--    </nav>-->
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
{% if user.is_authenticated %}
            <p>
                Welcome <b>{{ user.username }}!</b>
            </p>
            <div class="col-md-4">
                <p>
                    <a href="users/logout">Logout</a>
                </p>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="{% url 'quotes_list:create_quote' %}" role="button">Add quote</a>
                    <a href="{% url 'quotes_list:create_author' %}" role="button">Add author</a>
                </p>
            </div>
{% else %}
            <div style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
                <p>
                    <a href="{% url 'users:login' %}">Login</a>
                    <a href="{% url 'users:signup' %}">Registration</a>
                </p>
            </div>
{% endif %}
</body>
<main class="container">
    {% block content %} {% endblock %}
</main>

</html>

site_project/quotes_list/templates/quotes_list/create_author.html
{% extends "quotes_list/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_list:create_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Name author:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Date born:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Place, where was born:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
        <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

site_project/quotes_list/templates/quotes_list/create_quote.html
{% extends "quotes_list/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_list:create_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote author:
            <select name="author" required>
                {% for author in authors %}
                <option value="{{author.id}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px" width = 100%>
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

site_project/quotes_list/templates/quotes_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes_list/style.css' %}">
</head>

<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
{% if user.is_authenticated %}
            <p>
                Welcome <b>{{ user.username }}!</b>
            </p>
            <div class="col-md-4">
                <p>
                    <a href="users/logout">Logout</a>
                </p>
            </div>
            <div>
                <p>
                    <a href="{% url 'quotes_list:create_quote' %}" role="button">Add quote</a>
                    <a href="{% url 'quotes_list:create_author' %}" role="button">Add author</a>
                </p>
            </div>
<div><a href="script" style = "button">Load quotes and authors information</a></div>
<div><a href="users/script" style = "button">Load users information</a></div>
{% else %}
            <div style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
                <p>
                    <a href="users/login">Login</a>
                    <a href="users/signup">Registration</a>
                </p>
            </div>
   </div>
</div>
{% endif %}

{% for quote in quotes_list %}
<div class="row">
<!--    <div class="col-md-8">-->
    <div class="quote">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author}}</small>
        <a href="{% url 'quotes_list:author_details' quote.author.id %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag">{{tag.name}}</a>
            {% endfor %}
        </div>
    </div>
</div>
{% endfor %}
<!--    <nav>-->
<!--        <ul class="pager">-->
<!--            <li class="next">-->
<!--                <a href="next_page">Next <span aria-hidden="true">→</span></a>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </nav>-->

<!--    <div class="col-md-4 tags-box">-->
<!--            <h2>Top Ten tags</h2>-->
<!--            {% for tag in top_tags.all %}-->
<!--            <a class="tag" href="{% url 'quotes_list:tags_list' %}">{{tag.name}}</a>-->
<!--        {% endfor %}-->
<!--    </div>-->

</body>

site_project/quotes_list/templates/quotes_list/tag.html
{% extends "quotes_list/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes_list:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

site_project/quotes_list/templates/quotes_list/tags_list.html
{% extends "quotes_list/base.html" %}

{% block content %}

{% for quote in quotes %}
<div class="row">
<!--    <div class="col-md-8">-->
    <div class="quote">
        <span class="text" itemprop="text">{{quote.quote}}</span>
        <span>by <small class="author" itemprop="author">{{quote.author}}</small>
        <a href="{% url 'quotes_list:author_details' quote.author.id %}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag">{{tag.name}}</a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}